prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    retention: 1d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 500Mi

alertmanager:
  enabled: false

grafana:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  persistence:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

prometheusOperator:
  resources:
    requests:
      memory: 50Mi
      cpu: 25m
    limits:
      memory: 100Mi
      cpu: 50m
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi

kube-state-metrics:
  resources:
    requests:
      memory: 25Mi
      cpu: 25m
    limits:
      memory: 50Mi
      cpu: 50m

kubelet:
  enabled: false

kubeApiServer:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

defaultRules:
  create: false 