prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 200Mi
        cpu: 100m
    retention: 1d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 500Mi

alertmanager:
  enabled: false

grafana:
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 100Mi
      cpu: 100m
  persistence:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

prometheusOperator:
  resources:
    requests:
      memory: 50Mi
      cpu: 25m
    limits:
      memory: 100Mi
      cpu: 50m
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false

nodeExporter:
  enabled: true
  resources:
    requests:
      memory: 15Mi
      cpu: 25m
    limits:
      memory: 30Mi
      cpu: 50m

kubeStateMetrics:
  resources:
    requests:
      memory: 25Mi
      cpu: 25m
    limits:
      memory: 50Mi
      cpu: 50m

kube-state-metrics:
  resources:
    requests:
      memory: 25Mi
      cpu: 25m
    limits:
      memory: 50Mi
      cpu: 50m

kubelet:
  enabled: false

kubeApiServer:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

defaultRules:
  create: false 