apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: abstergo-app-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: abstergo-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s 