prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 200m
    retention: 1d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 100Mi
        cpu: 100m

grafana:
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m
  persistence:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

prometheusOperator:
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m

nodeExporter:
  resources:
    requests:
      memory: 30Mi
      cpu: 50m
    limits:
      memory: 50Mi
      cpu: 100m

kubeStateMetrics:
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 100Mi
      cpu: 100m 