apiVersion: apps/v1
kind: Deployment
metadata:
  name: abstergo-app
  labels:
    app: abstergo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abstergo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: abstergo-app
    spec:
      containers:
      - name: abstergo-app
        image: angreatharva/abstergo:46
        ports:
        - containerPort: 5173
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3 