apiVersion: apps/v1
kind: Deployment
metadata:
  name: abstergo-app
  labels:
    app: abstergo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abstergo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: abstergo-app
    spec:
      containers:
      - name: abstergo-app
        image: angreatharva/abstergo:63
        ports:
        - containerPort: 80
        - containerPort: 9113
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: metrics-server
        image: angreatharva/abstergo-metrics:59
        ports:
        - containerPort: 9113
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 9113
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3 