apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: abstergo-app-monitor
  namespace: monitoring
  labels:
    release: monitoring
    app: abstergo-app
spec:
  selector:
    matchLabels:
      app: abstergo-app
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics 