apiVersion: v1
kind: Service
metadata:
  name: abstergo-service
  labels:
    app: abstergo-app
spec:
  selector:
    app: abstergo-app
  ports:
  - port: 80
    targetPort: 5173
    name: web
  - port: 9113
    targetPort: 9113
    name: metrics
  type: LoadBalancer 